Vagrant.configure("2") do |c|
  c.berkshelf.enabled = false if Vagrant.has_plugin?("vagrant-berkshelf")
  c.vm.box = "tas50/windows_10"
  c.vm.synced_folder ".", "/vagrant", disabled: true
  c.vm.provider :virtualbox do |p|
    p.name = "kitchen-microsoft-windows-10-stig-baseline-vanilla-windows-10-00a6659d-6319-47ad-8b70-1b9bdd3ab3ff"
    p.customize ["modifyvm", :id, "--audio", "none"]
    p.customize ["modifyvm", :id, "--cpus", "2"]
    p.customize ["modifyvm", :id, "--memory", "4096"]
  end
end
